export const GET_DATA = "GET_DATA";
export const REQUEST_FOR_CURRENCY = "REQUEST_FOR_CURRENCY";
export const UPDATE_INPUTED_DATA = "UPDATE_INPUTED_DATA";
export const ADD_SELECT_VALUE = "ADD_SELECT_VALUE";
export const UPDATE_CURRENCY_SELECTOR = "UPDATE_CURRENCY_SELECTOR";
