export const GET_DATA = "GET_DATA";
export const UPLOAD_DATA_TO_CACHE = "UPLOAD_DATA_TO_CACHE";
export const REQUEST_FOR_CURRENCY = "REQUEST_FOR_CURRENCY";
export const UPDATE_INPUTED_DATA = "UPDATE_INPUTED_DATA";
export const ADD_SELECT_VALUE = "ADD_SELECT_VALUE";
